---
title: "simplePipes Examples"
author: "Craig A. Wendorf"
output:
  html_document:
    toc: true
    toc_float: true
    toc_depth: 4
    collapse: true
    theme: cerulean
    highlight: tango
    keep_md: TRUE
vignette: >
  %\VignetteIndexEntry{simplePipes Examples}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r,include=FALSE}
#suppress the warnings and other messages from showing in the knitted file.
knitr::opts_chunk$set(fig.width=7, fig.height=5,fig.path='figures/',echo=TRUE,warning=FALSE,message=FALSE)
```

```{r,include=FALSE}
library(simplePipes)
```

## simplePipes Examples

### Input Data

```{r}
variable=c(1,2,6,8,9,15)
variable1=c(1,2,6,8,9,15)
variable2=c(4,3,5,6,4,10)
frame=data.frame(variable1,variable2)
```

### Basic Pipes

#### Forward Basic Pipe

```{r}
mean(variable)
variable %>% mean
```

#### Backward Basic Pipe

```{r}
mean(variable)
mean %<% variable
```

### Dot Pipes

#### Forward Dot Pipe

```{r}
mean(variable,trim=.2)
variable %.>% mean(.,trim=.2)
variable %.>% mean(.,trim=.2) %.>% round(.,digits=1)
```

#### Backward Dot Pipe

```{r}
mean(variable,trim=.2)
mean(.,trim=.2) %<.% variable
round(.,digits=1) %<.% mean(.,trim=.2) %<.% variable
```

### Tee Pipe

#### Forward Tee Pipe

```{r,Forward-Tee-Plot}
plot(variable); mean(variable)
variable %T>% plot %>% mean
```

#### Backward Tee Pipe

```{r,Backward-Tee-Plot}
plot(variable); mean(variable)
plot %<T% variable %>% mean
```

### Wye Pipes

#### Forward Wye Pipe

```{r}
mean(variable); sd(variable)
variable %Y>% c(mean,sd)
```

#### Backward Wye Pipe

```{r}
mean(variable); sd(variable)
c(mean,sd) %<Y% variable
```

### Exposition Pipes

#### Forward Exposition Pipe

```{r}
with(frame,mean(variable2))
frame %$>% mean(variable2)
frame %$>% variable2 %>% mean
```

#### Backward Exposition Pipe

```{r}
with(frame,mean(variable2))
mean(variable2) %<$% frame
mean %<% variable2 %<$% frame
```

### Compound Assignment Pipe

```{r}
newvariable <- variable
newvariable %<>% mean
newvariable
```
