---
title: "Basic Pipes"
author: "Craig A. Wendorf"
output:
  html_document:
    toc: true
    toc_float: true
    toc_depth: 4
    collapse: true
    theme: cerulean
    highlight: tango
    keep_md: TRUE
vignette: >
  %\VignetteIndexEntry{Basic Pipes}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r,include=FALSE}
#suppress the warnings and other messages from showing in the knitted file.
knitr::opts_chunk$set(fig.width=7, fig.height=5,fig.path='figures/',echo=TRUE,warning=FALSE,message=FALSE)
```

```{r,include=FALSE}
library(simplePipes)
```

## Basic Pipes

### Input Data

First, name a `variable` and assign an array of values back to it.

```{r}
variable <- c(1,2,6,8,9,15)
```

### Standard R Syntax

In standard R syntax, get the `mean` of the `variable`.

```{r}
mean(variable)
```

### Forward Basic Pipe

Using the forward basic pipe, identify the `variable` and then get its `mean`.

```{r}
variable %>% mean
```

### Backward Basic Pipe

Using the backward basic pipe, get the `mean` of the `variable`.

```{r}
mean %<% variable
```
